name: Dreamcast Port CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      hdi_file:
        description: 'HDI ファイル名（リポジトリルート）'
        required: true
        default: '【PC98】雫.hdi'

jobs:
  extract-assets:
    name: Extract PC-98 HDI Assets
    runs-on: ubuntu-latest
    env:
      HDI_FILE: ${{ github.event.inputs.hdi_file || '【PC98】雫.hdi' }}
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-dev libpq-dev build-essential dosbox unzip \
            p7zip-full xorriso
          pip3 install --upgrade pip setuptools wheel pg8000

      - name: Extract raw assets from HDI
        run: |
          echo "Extracting assets from '$HDI_FILE'"
          mkdir -p assets/raw_gem assets/audio assets/tmp

          # 1) pc98-disk-tools を取得
          git clone --depth 1 https://github.com/barbeque/pc98-disk-tools.git tools/pc98-disk-tools

          # 2) HDI をフラットイメージに変換（出力先引数は無視される）
          cd tools/pc98-disk-tools
          python3 hdi_to_flat.py "$GITHUB_WORKSPACE/$HDI_FILE"
          # 生成された <basename>.img を assets/tmp/flat.img にリネーム
          HDI_BASENAME=$(basename "$HDI_FILE" .hdi)
          mv "${HDI_BASENAME}.img" "$GITHUB_WORKSPACE/assets/tmp/flat.img"
          cd ../..

          # 3) ループバックマウントして .GEM/.WAV を抽出
          sudo mkdir -p /mnt/pc98
          sudo mount -o loop,ro assets/tmp/flat.img /mnt/pc98
          find /mnt/pc98 -type f -iname '*.GEM' -exec cp {} assets/raw_gem/ \;
          find /mnt/pc98 -type f -iname '*.WAV' -exec mv {} assets/audio/ \;
          sudo umount /mnt/pc98
          rm -rf assets/tmp

      - name: Convert .GEM to PNG
        run: |
          if [ ! -f tools/convert_gem.py ]; then
            echo "Error: tools/convert_gem.py が見つかりません" >&2
            exit 1
          fi
          mkdir -p assets/images
          python3 tools/convert_gem.py assets/raw_gem assets/images

      - name: Extract scripts
        run: |
          mkdir -p assets/scripts
          python3 tools/extract_scripts.py "$HDI_FILE" > assets/scripts/story.txt

      - name: Upload extracted assets
        uses: actions/upload-artifact@v4
        with:
          name: shizuku-assets
          path: assets/

  build-dreamcast:
    name: Build Dreamcast VN
    runs-on: ubuntu-latest
    needs: extract-assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download extracted assets
        uses: actions/download-artifact@v4
        with:
          name: shizuku-assets
          path: assets/

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libsndfile1-dev libpng-dev

      - name: Setup KallistiOS
        run: |
          git clone --depth 1 https://github.com/KallistiOS/KallistiOS.git kos
          pushd kos
          make -j$(nproc)
          popd
          echo "KOS_BASE=$PWD/kos" >> $GITHUB_ENV

      - name: Setup ONScripter Dreamcast
        run: |
          git clone --depth 1 https://github.com/ogapee/onscripter.git onscripter-dc
          mkdir -p onscripter-dc/data
          cp -R assets/images/* onscripter-dc/data/
          cp -R assets/audio/* onscripter-dc/data/
          cp assets/scripts/story.txt onscripter-dc/data/

      - name: Build for Dreamcast
        env:
          KOS_BASE: ${{ env.KOS_BASE }}
        run: |
          pushd onscripter-dc
          make -f Makefile.dc dc
          popd

      - name: Upload Dreamcast CDI
        uses: actions/upload-artifact@v4
        with:
          name: shizuku-dreamcast-cdi
          path: onscripter-dc/bin/*.cdi
